# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='ocr',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\x12\x03ocr\"1\n\x08\x44\x61taPair\x12\x11\n\tdata_path\x18\x01 \x01(\t\x12\x12\n\ndata_label\x18\x02 \x01(\x05\"0\n\x0c\x44\x61taPairList\x12 \n\tdata_pair\x18\x01 \x03(\x0b\x32\r.ocr.DataPairb\x06proto3')
)




_DATAPAIR = _descriptor.Descriptor(
  name='DataPair',
  full_name='ocr.DataPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_path', full_name='ocr.DataPair.data_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_label', full_name='ocr.DataPair.data_label', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=68,
)


_DATAPAIRLIST = _descriptor.Descriptor(
  name='DataPairList',
  full_name='ocr.DataPairList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_pair', full_name='ocr.DataPairList.data_pair', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=118,
)

_DATAPAIRLIST.fields_by_name['data_pair'].message_type = _DATAPAIR
DESCRIPTOR.message_types_by_name['DataPair'] = _DATAPAIR
DESCRIPTOR.message_types_by_name['DataPairList'] = _DATAPAIRLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPair = _reflection.GeneratedProtocolMessageType('DataPair', (_message.Message,), dict(
  DESCRIPTOR = _DATAPAIR,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ocr.DataPair)
  ))
_sym_db.RegisterMessage(DataPair)

DataPairList = _reflection.GeneratedProtocolMessageType('DataPairList', (_message.Message,), dict(
  DESCRIPTOR = _DATAPAIRLIST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ocr.DataPairList)
  ))
_sym_db.RegisterMessage(DataPairList)


# @@protoc_insertion_point(module_scope)
